sonata_admin:
    title: 'SITS Bookings'
    title_logo: /img/fly-zermatt-logo.png
    show_mosaic_button: false
    security:
        handler: sonata.admin.security.handler.role

        role_admin: ROLE_USER
        role_super_admin: ROLE_SUPER_ADMIN

    options:
        dropdown_number_groups_per_colums:  2
        lock_protection: true
    #        form_type: 'horizontal'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
        groups:
            Booking Schedule:
                on_top:               true
                roles: [ROLE_USER]
                icon:                 '<i class="fa fa-calendar"></i>'
                items:
                    - route:        booking_custom_schedule
                      label:        BookingSchedule
            Create Voucher:
                on_top:               true
                roles: [ROLE_USER]
                icon:                 '<i class="fa fa-gift"></i>'
                items:
                    - route:        voucher_create
                      label:        Voucher
#            Booking Request:
#                on_top:               true
#                roles: [ROLE_USER]
#                icon:                 '<i class="fa fa-calendar-plus-o"></i>'
#                items:
#                    - route:        bookingrequest_list
#                      label:        BookingRequest
#            Waiting List:
#                on_top:               true
#                roles: [ROLE_USER]
#                icon:                 '<i class="fa fa-list"></i>'
#                items:
#                    - route:        waitinglist_list
#                      label:        Waiting List
            Reports:
#                on_top:               true
                roles: [ROLE_USER]
                icon:                 '<i class="fa fa-wpforms"></i>'
                items:
                    - route:        payment_type
                      label:        Payment Type Report
                      roles:        [ROLE_ADMIN]

#            My Availability:
#              on_top:               true
#              roles: [ROLE_USER]
#              icon:                 '<i class="fa fa-calendar-o"></i>'
#              items:
#                - route:        availability_list
#                  label:        Availability
            Application:
                icon:                 '<i class="fa fa-globe"></i>'
                roles: [ROLE_USER]
                items:
                    - admin.booking
                    - admin.bookingrequest
                    - admin.voucher

            Administration:
                icon:                 '<i class="fa fa-cogs"></i>'
                roles: [ROLE_ADMIN]
                items:
                    - admin.product
                    - admin.pilot
                    - admin.pilot.flight.commission

            System:
                icon:                 '<i class="fa fa-cogs"></i>'
                roles: [ROLE_SUPER_ADMIN]
                items:
                    - admin.availability
                    - admin.user
                    - admin.flight.schedule
                    - admin.product.category
                    - admin.meeting.location
                    - admin.booking.request.group.condition
                    - admin.payment.type
                    - admin.booking.owner
                    - admin.passenger

            Purchases & Payments:
                icon:                 '<i class="fa fa-money"></i>'
                roles: [ROLE_SUPER_ADMIN]
                items:
                    - admin.payment
                    - admin.purchase

    global_search:
        empty_boxes: fade
        case_sensitive: false

    templates:
        #        show:   '@App/Admin/display_client.html.twig'
        layout: '/base/standard_layout.html.twig'
        user_block: '/sonataadmin/Core/user_block.html.twig'
        button_create: '/sonataadmin/Button/create_button.html.twig'
#        edit: '/bundles/SonataAdminBundle/CRUD/edit.html.twig'

    assets:
        extra_stylesheets:
            - '//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/css/bootstrap-datepicker.css'
            - '//fonts.googleapis.com/css?family=Assistant'
            - '//fonts.googleapis.com/css?family=Roboto+Condensed'
            - '//fonts.googleapis.com/css?family=Play'
            - 'css/aazp.css'
            - 'css/aazp-legacy.css'
            - 'css/aazp-print.css'
#        javascripts:
#            extra_javascripts: 'js/aazp.js'

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
        sonata.admin.block.search_result:
            contexts:   [admin]
