twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        env: '%env(APP_ENV)%'

    form_themes:
        - '@SonataCore/Form/datepicker.html.twig'
        - bootstrap_3_layout.html.twig

    date:
#        format: d.m.Y, H:i:s
        timezone: Europe/Zurich

    number_format:
        decimals: 2
        decimal_point: '.'
        thousands_separator: ','
