<?php
namespace App\Repository;

use App\Entity\Availability;
use App\Entity\Pilot;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * AvailabilityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvailabilityRepository extends ServiceEntityRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, Availability::class);
    }


    public function getAvailabilityForPilotOnDate(Pilot $pilot, \DateTime $scheduleDate)
    {
        return $this->createQueryBuilder('a')
            ->where('a.pilot = :pilot')
            ->andWhere('a.unavailableFlightDate = :unavailableFlightDate')
            ->setParameter('pilot', $pilot )
            ->setParameter('unavailableFlightDate', $scheduleDate->format("Y-m-d") )
            ->orderBy('a.unavailableFlightDate', 'ASC')
            ->getQuery()
            ->setMaxResults(1)
            ->getOneOrNullResult();
    }
    
}
