<?php
namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BookingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookingRepository extends EntityRepository
{
    public function getBookingsForDate(\DateTime $today)
    {
        $enddate = clone $today;
        $enddate->modify('+ 1 days');

        return $this->createQueryBuilder('b')
            ->where('b.flightdate >= :startdate')
            ->andwhere('b.flightdate < :enddate')
            ->setParameter('startdate', $today->format('Y-m-d'))
            ->setParameter('enddate', $enddate->format('Y-m-d') )
            ->orderBy('b.meetingTime', 'ASC')
            ->getQuery()
            ->execute();
    }

    public function getBookingsForDateRange(\DateTime $startDate, \DateTime $endDate)
    {
        return $this->createQueryBuilder('b')
            ->where( 'b.flightdate between :startdate and :enddate')
            ->setParameter('startdate', $startDate->format('Y-m-d'))
            ->setParameter('enddate', $endDate->format('Y-m-d') )
            ->orderBy('b.meetingTime', 'ASC')
            ->getQuery()
            ->execute();
    }

    public function getBookingsForTheLastDays(\DateTime $givenDate, $noOfDays)
	{
	    $givenDate->modify('- '.$noOfDays.' days');
	    return $this->createQueryBuilder('b')
	    ->where('b.created >= :fromdate')
	    ->setParameter('fromdate', $givenDate->format('Y-m-d') )
	    ->orderBy('b.created', 'DESC')
	    ->getQuery()
	    ->execute();
	}
}
