<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FlightScheduleTimeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FlightScheduleTimeRepository extends EntityRepository
{

    public function getFlightScheduleTimesFor(\DateTime $scheduleDate)
    {
        return $this->createQueryBuilder('ft')
        ->join('ft.flightSchedule', 'fs')
        ->where('fs.affectiveStartDate <= :now')
        ->andWhere('fs.affectiveEndDate >= :now')
        ->setParameter('now', $scheduleDate->format("Y-m-d"))
        ->orderBy('ft.scheduleStartTime', 'ASC')
        ->getQuery()
        ->execute();
    }
    
}
