<?php
namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MeetingLocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeetingLocationRepository extends EntityRepository
{
    public function getPreferredMeetingLocations()
    {
        $preferredMeetingLocations = $this
        ->createQueryBuilder('ml')
        ->where('ml.preferred = :preferred')
        ->setParameter('preferred', true)
        ->orderBy('ml.sortOrder', 'ASC')
        ->getQuery()
        ->execute();
    
        return $preferredMeetingLocations;
    }
}
