<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;
use App\Entity\Pilot;

/**
 * PassengerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PassengerRepository extends EntityRepository
{
    public function getPassengersForPilotOnADate(Pilot $pilot, $givenDate)
    {
        $givenEndDate = clone $givenDate;
        $givenEndDate = $givenEndDate->modify('+ 1 days');

        return $this->createQueryBuilder('p')
                ->leftJoin('p.pilot', 'pi')
                ->leftJoin('p.flight', 'f')
                ->leftJoin('p.purchase', 'pu')
                ->Join('p.booking', 'b')
                ->where('b.flightdate >= :startdate')
                ->andWhere('b.flightdate < :enddate')
                ->andWhere('pi.id = :pilot')
                ->setParameter('startdate', $givenDate->format("Y-m-d"))
                ->setParameter('enddate', $givenEndDate->format("Y-m-d"))
                ->setParameter('pilot', $pilot)
                ->orderBy('b.meetingTime', 'ASC')
                ->getQuery()
                ->execute();
    }
}
