<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PaymentTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentTypeRepository extends EntityRepository
{
    public function getSumUpTypePayments()
    {
        return $this->createQueryBuilder('pt')
        ->where('pt.sumUpPayment = :sumUpPayment')
        ->setParameter('sumUpPayment', true)
        ->getQuery()
        ->execute();
    }
}
