<?php
namespace App\Repository;

use Doctrine\ORM\EntityRepository;
use App\Entity\Pilot;
use App\Entity\Product;

/**
 * PilotFlightCommissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PilotFlightCommissionRepository extends EntityRepository
{
    public function getPilotFlightCommission(Pilot $pilot, Product $flight)
    {
        return $this->createQueryBuilder('pfc')
            ->where('pfc.pilot = :pilot')
            ->andWhere('pfc.flight = :flight')
            ->setParameter('pilot', $pilot)
            ->setParameter('flight', $flight)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
