<?php
namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PilotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PilotRepository extends EntityRepository
{
    public function getFlyZermattPilots()
    {
        return $this->createQueryBuilder('p')
        ->where('p.flyZermattPilot = :flyZermattPilot')
        ->setParameter('flyZermattPilot', true)
        ->getQuery()
        ->execute();
    }
}
