<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PurchaseItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PurchaseItemRepository extends EntityRepository
{
}
