<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;
use App\Entity\Pilot;

/**
 * PurchaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PurchaseRepository extends EntityRepository
{

    public function getAllFlightsForPilotOverDateRange(Pilot $pilot, $startDate, $endDate)
    {
        return $this->createQueryBuilder('pu')
        ->leftJoin('pu.purchaseItems', 'pi')
        ->leftJoin('pi.product', 'pr')
        ->leftJoin('pr.productCategory', 'pc')
        ->leftJoin('pu.passenger', 'pa')
        ->leftJoin('pa.pilot', 'p')
        ->leftJoin('pa.booking', 'b')
        ->where('p.id = :pilot')
        ->andWhere('b.flightdate between :startDate AND :endDate')
        ->andWhere('pc.id = 1')
        ->setParameter('pilot', $pilot)
        ->setParameter('startDate', $startDate)
        ->setParameter('endDate', $endDate)
        ->getQuery()
        ->execute();
    }

}
