<?php
namespace App\Controller;

use App\Entity\User;
use App\Entity\Voucher;
use App\Form\UserType;
use Sonata\AdminBundle\Controller\CRUDController;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;

class UserCRUDController extends CRUDController
{
    public function createAction()
    {
//        parent::createAction(); // TODO: Change the autogenerated stub
//            $request = Request::createFromGlobals();
//
//        $user = new User();
//
//        $form = $this->createForm(UserType::class, $user);
//        $form->remove('roles');
//        $form->remove('pilot');
//        $form->add('save', SubmitType::class);
//        $form->handleRequest($request);
//
        //        $em = $this->getDoctrine()->getManager();
//        $voucher = $em->getRepository(Voucher::class)->find($id);
//
//        if (!$voucher)
//        {
//            throw $this->createNotFoundException('Unable to find Voucher entity.');
//        }
//
//        $voucher->setFlightdate(new \DateTime);
//        $em->persist($voucher);
//        $em->flush();
//
//        $this->addFlash('sonata_flash_success','Voucher has been successfully redeemed!');

        return $this->redirectToRoute('security_user_create');
    }

}
