# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

#    App\Service\MarkdownHelper:
#        arguments:
#            $logger: '@monolog.logger.markdown'


    admin.bookingscheduleview:
        class: App\Admin\BookingScheduleViewAdmin
        arguments:
            -
            -
            - App\Controller\BookingScheduleViewCRUDController
        tags:
            - { name: sonata.admin, manager_type: orm, label: Booking Schedule}
        public: true

    admin.bookingrequest:
        class: App\Admin\BookingRequestAdmin
        arguments:
            -
            - App\Entity\BookingRequest
            -
        tags:
            - { name: sonata.admin, manager_type: orm, group: Admin, label: Booking Request, pager_type: 'simple' }
        public: true

    admin.waitinglist:
        class: App\Admin\WaitingListAdmin
        arguments:
            -
            - App\Entity\WaitingListItem
            -
        tags:
            - { name: sonata.admin, manager_type: orm, label: Waiting List }
        public: true

    admin.voucher:
        class: App\Admin\VoucherAdmin
        arguments:
            -
            - App\Entity\Voucher
            -
        tags:
            - { name: sonata.admin, manager_type: orm, group: Admin, label: Voucher, pager_type: 'simple' }
        public: true

    admin.passenger:
        class: App\Admin\PassengerAdmin
        arguments:
            -
            - App\Entity\Passenger
            -
        tags:
            - { name: sonata.admin, manager_type: orm, group: Admin, label: Passenger }
        public: true

    admin.booking:
        class: App\Admin\BookingAdmin
        arguments:
            -
            - App\Entity\Booking
            -
        tags:
            - { name: sonata.admin, manager_type: orm, group: Admin, label: Booking, pager_type: 'simple' }
        public: true

    admin.pilot:
        class: App\Admin\PilotAdmin
        arguments:
            -
            - App\Entity\Pilot
            -
        tags:
            - { name: sonata.admin, manager_type: orm, group: Admin,  label: Pilot }
        public: true

    admin.user:
        class: App\Admin\UserAdmin
        arguments:
            -
            - App\Entity\User
            -
        tags:
            - { name: sonata.admin, manager_type: orm, group: Admin,  label: User }
        public: true

