# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

#    App\Service\MarkdownHelper:
#        arguments:
#            $logger: '@monolog.logger.markdown'


    admin.bookingrequest:
        class: App\Admin\BookingRequestAdmin
        arguments:
            -
            - App\Entity\BookingRequest
            -
        tags:
            - { name: sonata.admin, manager_type: orm, group: Admin, label: Booking Requests, pager_type: 'simple' }
        public: true

    admin.waitinglist:
        class: App\Admin\WaitingListAdmin
        arguments:
            -
            - App\Entity\WaitingListItem
            -
        tags:
            - { name: sonata.admin, manager_type: orm, label: Waiting List }
        public: true

    admin.voucher:
        class: App\Admin\VoucherAdmin
        arguments:
            -
            - App\Entity\Voucher
            - App\Controller\VoucherCRUDController
        tags:
            - { name: sonata.admin, manager_type: orm, group: Admin, label: Vouchers }
        public: true

    admin.passenger:
        class: App\Admin\PassengerAdmin
        arguments:
            -
            - App\Entity\Passenger
            -
        tags:
            - { name: sonata.admin, manager_type: orm, group: Admin, label: Passengers, pager_type: 'simple' }
        public: true

    admin.booking:
        class: App\Admin\BookingAdmin
        arguments:
            -
            - App\Entity\Booking
            -
        tags:
            - { name: sonata.admin, manager_type: orm, group: Admin, label: Bookings, pager_type: 'simple' }
        public: true

    admin.booking.owner:
        class: App\Admin\BookingOwnerAdmin
        arguments:
            -
            - App\Entity\BookingOwner
            -
        tags:
            - { name: sonata.admin, manager_type: orm, group: Admin, label: Booking Owner }
        public: true

    admin.product:
        class: App\Admin\ProductAdmin
        arguments:
            -
            - App\Entity\Product
            -
        tags:
            - { name: sonata.admin, manager_type: orm, group: Admin,  label: Products }
        public: true

    admin.product.category:
        class: App\Admin\ProductCategoryAdmin
        arguments:
            -
            - App\Entity\ProductCategory
            -
        tags:
            - { name: sonata.admin, manager_type: orm, group: Admin,  label: Product Categorys }
        public: true

    admin.purchase:
        class: App\Admin\PurchaseAdmin
        arguments:
            -
            - App\Entity\Purchase
            -
        tags:
            - { name: sonata.admin, manager_type: orm, group: Admin,  label: Purchases, pager_type: 'simple'  }
        public: true

    admin.purchaseitem:
        class: App\Admin\PurchaseItemAdmin
        arguments:
            -
            - App\Entity\PurchaseItem
            -
        tags:
            - { name: sonata.admin, manager_type: orm, group: Admin,  label: PurchaseItems, pager_type: 'simple'  }
        public: true

    admin.payment:
        class: App\Admin\PaymentAdmin
        arguments:
            -
            - App\Entity\Payment
            -
        tags:
            - { name: sonata.admin, manager_type: orm, group: Admin,  label: Payments, pager_type: 'simple'  }
        public: true

    admin.payment.type:
        class: App\Admin\PaymentTypeAdmin
        arguments:
            -
            - App\Entity\PaymentType
            -
        tags:
            - { name: sonata.admin, manager_type: orm, group: Admin,  label: Payment Type  }
        public: true

    admin.meeting.location:
        class: App\Admin\MeetingLocationAdmin
        arguments:
            -
            - App\Entity\MeetingLocation
            -
        tags:
            - { name: sonata.admin, manager_type: orm, group: Admin,  label: Meeting Location's }
        public: true

    admin.booking.request.group.condition:
        class: App\Admin\BookingRequestGroupConditionAdmin
        arguments:
            -
            - App\Entity\BookingRequestGroupCondition
            -
        tags:
            - { name: sonata.admin, manager_type: orm, group: Admin, label: Booking Request Group Condition's }
        public: true

    admin.flight.schedule:
        class: App\Admin\FlightScheduleAdmin
        arguments:
            -
            - App\Entity\FlightSchedule
            -
        tags:
            - { name: sonata.admin, manager_type: orm, group: Admin, label: Flight Schedules }
        public: true

    admin.pilot:
        class: App\Admin\PilotAdmin
        arguments:
            -
            - App\Entity\Pilot
            -
        tags:
            - { name: sonata.admin, manager_type: orm, group: Admin,  label: Pilot's }
        public: true

    admin.pilot.flight.commission:
        class: App\Admin\PilotFlightCommissionAdmin
        arguments:
            -
            - App\Entity\PilotFlightCommission
            -
        tags:
            - { name: sonata.admin, manager_type: orm, group: Admin,  label: Pilot Commission }
        public: true

    admin.availability:
        class: App\Admin\AvailabilityAdmin
        arguments:
            -
            - App\Entity\Availability
            -
        tags:
            - { name: sonata.admin, manager_type: orm, group: Admin,  label: Availability, pager_type: 'simple' }
        public: true

    admin.user:
        class: App\Admin\UserAdmin
        arguments:
            -
            - App\Entity\User
            - App\Controller\UserCRUDController
        tags:
            - { name: sonata.admin, manager_type: orm, group: Admin,  label: Users }
        public: true

